### ISSUE TITLE
Improvements for SDK

### ISSUE THREAD

**Issue by buster92** [QuantiModo/QuantiModo-SDK-Android#14]
1. Try to implement native authentication for Quantimodo. Depends on point 2. 8-16

2. Implement token management inside the SDK, that means, getting the auth code, then get the access token and then the refreshing. Also the calls to the services shouldn't include the token as parameter. 

12
  2.1. Improve QuantimodoApiV2 to really work as a Singleton (Need More Discussion)
  2.2. Remove deprecated getToken method AuthHelper (TODO)
  2.3. Implement methods to expose authentication API Services  (Create issue with more detail)
  2.4. Refresh the token when neccesary (DONE)

3. Set up and encapsulate ToolsPrefs and AppModule. The goal is to have everything inside of QBaseApplication/Qtools project. 15 - 20
In the practice the user should have to just initialize the SDK passing the client_id and client_secret on the Application class
  3.1. Move ToolsPrefs, AppModule and QSpiceService set up, to QBaseApplication (Create issue with more detail)
  3.2. Remove Dagger dependency for client apps  (Create issue with more detail)
  3.3. Improve SyncService, so the user shouldn't have to store the data manually. Evaluate the usage of a separated database, or set up the name of it at first when initializing the SDK  (CANCELED)

5.  Document the public methods/classes/etc so for the client will be clear about what every component does Document every method the most clear possible (Create Issue)

4. Make the Qtools components (Fragments and Activities) customizable 8-12  (BACKLOG)
Create customizable buttons, text colors, text sizes  
Posibility to cutomize the activities titles/names 

Final goal, have an SDK where the user has just to add the dependency and set up the QBaseApplication. Optionally customize the components

**Comment by Toseter** [comment]
>Implement token management inside the SDK, that means, getting the auth code, then get the access token and then the refreshing. Also the calls to the services shouldn't include the token as parameter.

Agree, when introduced V2 version, this was intended, but at that time we used Accounts mechanism for token management.  

>2.1. Improve QuantimodoApiV2 to really work as a Singleton 

What we would gain with that?

>2.2. Validate the token on each request

Currently all requests that go through SpiceService checks token every time. ( See AuthHelper.getAuthTokenWithRefresh )

>2.3. Implement methods to expose authentication API Services

What do you mean by that?

>2.4. Refresh the token when neccesary

Already implemented in AuthHelper.getAuthTokenWithRefresh

>Set up and encapsulate ToolsPrefs and AppModule. The goal is to have everything inside of QBaseApplication/Qtools project. 15 - 20
In the practice the user should have to just initialize the SDK passing the client_id and client_secret on the Application class
3.1. Move ToolsPrefs, AppModule and QSpiceService set up, to QBaseApplication
3.2. Remove Dagger dependency for client apps
3.3. Improve SyncService, so the user shouldn't have to store the data manually. Evaluate the usage of a separated database, or set up the name of it at first when initializing the SDK
3.4. Document the public methods/classes/etc so for the client will be clear about what every component does

Why do we need that? 
SDK working separately from QTools because of this.
QTools is like micro-framework for apps like MoodiModo, if you check QM-Android application, you can see that it using Qtools.

Dependency injection needed to decouple implementation, for example MoodiModo using custom AuthHelper. It could be any framework, not only Dagger.

For SDK you need pass just client_id and client_secret , and token for now.
 

>3.3. Improve SyncService, so the user shouldn't have to store the data manually. Evaluate the usage of a separated database, or set up the name of it at first when initializing the SDK

Currently working on this, but this would be one database that would fit to any variables. 
SyncService not intended to store data, it used to sync data. 


>Make the Qtools components (Fragments and Activities) customizable 8-12
4.1. Create customizable buttons, text colors, text sizes
4.2. Posibility to cutomize the activities titles/names

What do you mean by that?
You can always provide new layout, or just extend existing component.

**Comment by buster92** [comment]
Thanks Aleksey
Well when I said to make QuantimodoAPiV2 class as a Singleton, was because I wanted to avoid memory usage, and also be sure that we have just one instance.

About refreshing token on each request, I know there is getTokenWithRefresh method, but I found out that you are right, because SkdRequest.getToken calls getTokenWithRefresh, so we just have to delete AuthHelper.getAuthToken method to avoid problems.

on Implement methods to expose authentication API Services I meant encapsulate on QuantimodoApiV2 services like oauth2/authorize and oauth2/token

On the other points I want to avoid the cost of adding the Quantimodo SDK to a new project, trying to set up and manage the most possible on the Qtools

About the customize view yeah you can extend a class but I want to have something more stylable, so the client can have the Qtools components look as if they were completely part of his app.
